### ISSUE TITLE
cannot setup bambu

### ISSUE THREAD

**Issue by joker97max** [ferrandi/PandA-bambu#19]
before 2nd step for install Bambu i see that:

~/Projects/panda-0.9.6/obj$ ../configure --prefix=/opt/panda --enable-flopoco --enable-icarus --enable-verilator --enable-xilinx --enable-modelsim --enable-altera --enable-opt --enable-lattice --enable-release --with-mentor-license=license-string
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to create a pax tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of g++... gcc3
checking for gcc... gcc
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for gawk... (cached) mawk
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for flex... flex
checking lex output file root... lex.yy
checking lex library... -lfl
checking whether yytext is a pointer... yes
checking for bison... bison -y
checking for g77... no
checking for xlf... no
checking for f77... no
checking for frt... no
checking for pgf77... no
checking for cf77... no
checking for fort77... no
checking for fl32... no
checking for af77... no
checking for xlf90... no
checking for f90... no
checking for pgf90... no
checking for pghpf... no
checking for epcf90... no
checking for gfortran... no
checking for g95... no
checking for xlf95... no
checking for f95... no
checking for fort... no
checking for ifort... no
checking for ifc... no
checking for efc... no
checking for pgfortran... no
checking for pgf95... no
checking for lf95... no
checking for ftn... no
checking for nagfor... no
checking whether we are using the GNU Fortran 77 compiler... no
checking whether  accepts -g... no
checking if g++ supports C++17 features without additional flags... no
checking if g++ supports C++17 features with -std=c++17... yes
checking if g++ supports C++17 features with -std=gnu++17... yes
checking if g++ supports C++11 features without additional flags... no
checking if g++ supports C++11 features with -std=c++11... yes
checking if g++ supports C++11 features with -std=gnu++11... yes
checking if g++ supports C++0x features without additional flags... yes
checking if g++ supports C++0x features with -std=c++0x... yes
checking if g++ supports hexfloat features without additional flags... yes
checking if g++ supports hexfloat features with -std=c++0x flag... yes
checking if g++ supports hexfloat features with -std=c++11 flag... yes
checking whether NLS is requested... yes
checking for msgfmt... no
checking for gmsgfmt... :
checking for xgettext... no
checking for msgmerge... no
checking for pow in -lm... yes
checking for gzopen in -lz... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for ANSI C header files... (cached) yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking sys/timeb.h usability... yes
checking sys/timeb.h presence... yes
checking for sys/timeb.h... yes
checking zlib.h usability... yes
checking zlib.h presence... yes
checking for zlib.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking getopt.h usability... yes
checking getopt.h presence... yes
checking for getopt.h... yes
checking for sys/wait.h that is POSIX.1 compatible... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for size_t... (cached) yes
checking for working volatile... yes
checking size of unsigned long... 8
checking for error_at_line... yes
checking whether gcc needs -traditional... no
checking for working strtod... yes
checking for floor... yes
checking for memset... yes
checking for modf... yes
checking for pow... yes
checking for sqrt... yes
checking for strchr... yes
checking for strcasecmp... yes
checking return type of signal handlers... void
checking whether struct tm is in sys/time.h or time.h... time.h
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for shl_load... no
checking for shl_load in -ldld... no
checking for dlopen... no
checking for dlopen in -ldl... yes
checking whether a program can dlopen itself... yes
checking whether a statically linked program can dlopen itself... no
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether we are building for a Win32 host... no
checking for doxygen... /usr/bin/doxygen
checking for dot... YES
checking for svnversion... no
checking for boostlib >= 1.48.0... yes
checking whether the Boost::System library is available... yes
checking for main in -lboost_system... yes
checking whether the Boost::Date_Time library is available... yes
checking for exit in -lboost_date_time... yes
checking whether the Boost::Filesystem library is available... yes
checking for main in -lboost_filesystem... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking if -DBOOST_NO_SCOPED_ENUMS or BOOST_NO_CXX11_SCOPED_ENUMS is required... no
checking if -rpath is fine... yes
checking linux distribution... ubuntu_20.04
checking if directory is a git repository... no
checking if directory is a git worktree... no
checking bdd.h usability... yes
checking bdd.h presence... yes
checking for bdd.h... yes
checking fdd.h usability... yes
checking fdd.h presence... yes
checking for fdd.h... yes
checking bvec.h usability... yes
checking bvec.h presence... yes
checking for bvec.h... yes
checking if ALTERA quartus_sh is present in /opt/altera/*... no
checking if ALTERA quartus_sh is present in /opt/intelFPGA/*... no
configure: error: ALTERA settings script required

**Comment by joker97max** [comment]
this libs i'm install

- autoconf
- autoconf-archive
- automake
- libtool
- g++ from 7 to 10
- gcc- from 7 to 10
- gcc-like as-plugin-dev
- gcc-like as-multilib
- g++-like as-multilib
- gfortran-like as
- clang-like as
- libclang-like as-dev
- libbdd-dev
- libboost-all-dev
- libmpc-dev
- libmpfr-dev
- libxml2-dev
- liblzma-dev
- libmpfi-dev
- zlib1g-dev
- libicu-dev
- bison
- doxygen
- flex
- graphviz
- iverilog
- verilator
- pkg-config
- libsuitesparse-dev
- libglpk-dev
- make

**Comment by ferrandi** [comment]
Dear Max,
from the options you passed to the configure, it seems that you have just copied the options suggested by the INSTALL file. This way is possible only in case you have all the tools installed on your system.
For example, passing --enable-altera requires to have Intel/Altera tools installed. In case you do not have such a tool, please remove such option. Same thing for -enable-xilinx --enable-modelsim --enable-altera --enable-lattice --with-mentor-license=license-string.
Cheers,
Fabrizio

**Comment by joker97max** [comment]
Okey, thanks for answer, Fabrizio.

**Comment by ferrandi** [comment]
I'm going to close since it seems that it is just a misinterpretation of the INSTALL instructions.
