### ISSUE TITLE
New Devices Support

### ISSUE THREAD

**Issue by LZYfdu** [ferrandi/PandA-bambu#207]
Hello,
I've looked at the example for adding a new device. And I'm wondering how can I get the corresponding xml file if I need to support a new family of FPGAs or ASICs such as those from other companies.
What information do I need to know about the device? And do I need support from the manufacturer?

**Comment by LZYfdu** [comment]
After reading the code I found that IPs can be synthesized through a script that generates xml files.

**Comment by fabrizioferrandi** [comment]
Please have a look at: https://github.com/ferrandi/PandA-bambu/tree/main/documentation/bambu101/new_device_support
More complex things may require tight cooperation with us.
