### ISSUE TITLE
Fully associative cache issue

### ISSUE THREAD

**Issue by Ansaya** [ferrandi/PandA-bambu#278]
The fully associative cache generated using the following command line results in a simulation error for an out-of-bounds read memory operation:
panda_regressions/hls/bambu_interface_test/2mm.c --top-fname=mmult --generate-tb=panda_regressions/hls/bambu_interface_test/2mm.c -DFULLY_ASS --generate-interface=INFER --simulate --compiler=I386_CLANG6 -O2 --experimental-setup=BAMBU-BALANCED-MP

**Comment by gggg100** [comment]
Solved
