### ISSUE TITLE
Create tag and release for version 2024.2

### ISSUE THREAD

**Issue by zebreus** [ferrandi/PandA-bambu#295]
04123a3edb37040db52c44f6591006391cf4a90b seems to release version 2024.2 but the commit is not tagged. I am currently working on packaging bambu for nix and a recent tagged commit would make that easier.

**Comment by Ansaya** [comment]
There was a little delay, but here you go [v2024.03](https://github.com/ferrandi/PandA-bambu/releases/tag/v2024.03).

**Comment by zebreus** [comment]
Thank you
