### ISSUE TITLE
Incompatible data types during testbench generation

### ISSUE THREAD

**Issue by DavErrico** [ferrandi/PandA-bambu#44]
Hi everybody,

I have generated the HDL code of my project and I'm trying to simulate it. However, I'm facing an issue with the .xml file because of compatibility with the data types. The interface of the network generated by Bambu requires fixed point data

`void myproject(ac_fixed<32, 6, true, (ac_q_mode)0, (ac_o_mode)0>*, ac_fixed<32, 6, true, (ac_q_mode)1, (ac_o_mode)1>*, unsigned short&, unsigned short&); 
`

while the test.xml I'm using is like the following:

```
<?xml version="1.0"?>
<function>
  <testbench input_layer="{0.794551,1.01644,..}"
    layer18_out="{0.688477,0.139648,..}"
    const_size_in_1="15360"
    const_size_out_1="240"/>
</function>
```
[out_new.log](https://github.com/ferrandi/PandA-bambu/files/7717458/out_new.log)
[test_xml.txt](https://github.com/ferrandi/PandA-bambu/files/7717470/test_xml.txt)
[myproject_cpp.txt](https://github.com/ferrandi/PandA-bambu/files/7717479/myproject_cpp.txt)

So I'm asking you if there is a way to convert the floating point data to fixed point in the .xml file in order to match the network interface. You can find the output log and the test.xml file in the attachment. Thank you for your help.

Kind regards,
Davide Errico

**Comment by Ansaya** [comment]
Hi Davide,
thank you for using our framework. I need you to share a little more information so that I can reproduce your issue and help you solve it.
Please let me know what is the full command line you call bambu with and share all the files needed to compile myproject.cpp (maybe an archive with all the necessary data).

Best regards,
Michele.

**Comment by DavErrico** [comment]
Hi Michele,

thank you for your reply. I wrote you an e-mail where you can find the complete project archive with all the information required to reproduce the issue I'm facing. I look forward to hearing from you. Thank you for your help.

Kind regards,
Davide Errico
