### ISSUE TITLE
Extend Vitis HLS RTL Blackbox with Olympus attributes

### ISSUE THREAD

**Issue by Ansaya** [ferrandi/PandA-bambu#87]
Vitis HLS RTL Blackbox JSON file needs to be extended to support integration with Olympus. 
Extension just requires the addition of some new fields in the Blackbox JSON description as follows:
 - "param_type": top-level field (same level as "c_function_name")
   - "mm" if parameters use regular memory-mapped arrays (i.e. arr[10])
   - “stream” if parameters use streams/fifos 
 - For every c_parameter entry (same level as "c_name" and "c_port_direction")
   - “c_type”: the type the data would have in C (i.e. “double”, “uint32_t”, “ap_int<17>”) (this is really to detect the bitwidth, so if you’re using a custom-width type, the important thing is the first number in the type name is the bitwidth)
   - “depth”: the number of elements in the array (i.e. 1331)

Actions:

- [x] #86 
- [ ] Extend the --generate-interface option
- [ ] Integrate Olympus fields into the RTL Blackbox JSON file when required

**Comment by SerenaC94** [comment]
This is obsolete, Olympus no longer expects a JSON file.
